export const mockEvents = {
 city: {
    id: 1007700,
    city: 'München',
    lat: 48.14,
    lon: 11.58,
    state: "",
    country: "de",
    zip: "meetup3",
    member_count: 1257
 },
 events: [
 {
 created: 1371224928000,
 id: "drpzdgyzpbrb",
 name: "Ruby User Group Meetup Munich",
 date_in_series_pattern: false,
 status: "upcoming",
 time: 1573668000000,
 local_date: "2019-11-13",
 local_time: "19:00",
 updated: 1507810525000,
 utc_offset: 3600000,
 waitlist_count: 0,
 yes_rsvp_count: 3,
 group: {
 created: 1370808069000,
 name: "Munich Rubyshift, Ruby User Group",
 "id": 8851722,
 "join_mode": "open",
 "lat": 48.13999938964844,
 "lon": 11.579999923706055,
 "urlname": "Munich-Rubyshift-Ruby-User-Group",
 "who": "Rubyists",
 "localized_location": "München, Germany",
 "state": "",
 "country": "de",
 "region": "en_US",
 "timezone": "Europe/Berlin"
 },
 "link": "https://www.meetup.com/Munich-Rubyshift-Ruby-User-Group/events/drpzdgyzpbrb/",
 "description": "<p>We're actively searching for speakers! Want to become one? Ping us!</p> ",
 "visibility": "public",
 "member_pay_fee": false
 },
 {
 "created": 1571344936000,
 "duration": 7200000,
 "id": "265751488",
 "name": "Winter is coming - Serverless is prepared",
 "date_in_series_pattern": false,
 "status": "upcoming",
 "time": 1573061400000,
 "local_date": "2019-11-06",
 "local_time": "18:30",
 "updated": 1571345988000,
 "utc_offset": 3600000,
 "waitlist_count": 0,
 "yes_rsvp_count": 80,
 "venue": {
 "id": 26219453,
 "name": "Oskar-von-Miller-Ring 20",
 "lat": 48.1448974609375,
 "lon": 11.57638931274414,
 "repinned": true,
 "address_1": "Oskar-von-Miller-Ring 20",
 "city": "München",
 "country": "de",
 "localized_country_name": "Germany"
 },
 "group": {
 "created": 1473068565000,
 "name": "Serverless Munich",
 "id": 20389664,
 "join_mode": "open",
 "lat": 48.13999938964844,
 "lon": 11.579999923706055,
 "urlname": "Serverless-Munich",
 "who": "Members",
 "localized_location": "München, Germany",
 "state": "",
 "country": "de",
 "region": "en_US",
 "timezone": "Europe/Berlin"
 },
 link: "https://www.meetup.com/Serverless-Munich/events/265751488/",
 description: '<p>This season we found a small cosy vendor who will give us shelter in front of the fireplace...</p>',
 how_to_find_us: "AWS Office, 1st Floor",
 "visibility": "public",
 "member_pay_fee": false
 },
 {
 "created": 1564472388000,
 "duration": 30600000,
 "id": "263577205",
 "name": "Global Day of Coderetreat @ ThoughtWorks Munich",
 "rsvp_limit": 70,
 "date_in_series_pattern": false,
 "status": "upcoming",
 "time": 1573889400000,
 "local_date": "2019-11-16",
 "local_time": "08:30",
 "rsvp_open_offset": "PT673H",
 "updated": 1564748617000,
 "utc_offset": 3600000,
 "waitlist_count": 0,
 "yes_rsvp_count": 38,
 "venue": {
 "id": 25852478,
 "name": "ThoughtWorks Munich ",
 "lat": 48.135372161865234,
 "lon": 11.613633155822754,
 "repinned": true,
 "address_1": "Bothestraße 11",
 "city": "München",
 "country": "de",
 "localized_country_name": "Germany"
 },
 "group": {
 "created": 1413448074000,
 "name": "ThoughtWorks Munich",
 "id": 17658472,
 "join_mode": "open",
 "lat": 48.13999938964844,
 "lon": 11.579999923706055,
 "urlname": "ThoughtWorks-Muenchen",
 "who": "Mitglieder",
 "localized_location": "München, Germany",
 "state": "",
 "country": "de",
 "region": "en_US",
 "timezone": "Europe/Berlin"
 },
 "link": "https://www.meetup.com/ThoughtWorks-Muenchen/events/263577205/",
 description: "<p>Welcome to the Global Day of Coderetreat in Munich on Saturday November 16th at ThoughtWorks Munich!</p> <p>On Saturday, November 16th...</p>",
 visibility: "public",
 "member_pay_fee": false
 },
 {
 "created": 1571209775000,
 "duration": 9000000,
 "id": "265706638",
 "name": "Evening Workshop on: 'Developing a Coaching Culture in your organisation'",
 "rsvp_limit": 50,
 "date_in_series_pattern": false,
 "status": "upcoming",
 "time": 1573752600000,
 "local_date": "2019-11-14",
 "local_time": "18:30",
 "updated": 1571209801000,
 "utc_offset": 3600000,
 "waitlist_count": 2,
 "yes_rsvp_count": 50,
 "venue": {
 "id": 25615449,
 "name": "Henley Business School Germany",
 "lat": 48.13788604736328,
 "lon": 11.583979606628418,
 "repinned": true,
 "address_1": "Maximilianstraße 40",
 "city": "München",
 "country": "de",
 "localized_country_name": "Germany"
 },
 "group": {
 "created": 1510684582000,
 "name": "Leadership Events - München",
 "id": 26598849,
 "join_mode": "open",
 "lat": 48.13999938964844,
 "lon": 11.579999923706055,
 "urlname": "Leadership-Events-Munchen",
 "who": "Mitglieder",
 "localized_location": "München, Germany",
 "state": "",
 "country": "de",
 "region": "en_US",
 "timezone": "Europe/Berlin"
 },
 link: "https://www.meetup.com/Leadership-Events-Munchen/events/265706638/",
 description: "<p>Many organisations are discussing how they can develop a coaching culture. But what does this mean in practice?...</p>",
 What3words: "///gams.aufheben.alge",
 "visibility": "public",
 "member_pay_fee": false
 },
 {
 "created": 1571563126000,
 "duration": 7200000,
 "id": "265811041",
 "name": "ThoughtWorks University - Wie starte ich meine Karriere in der IT-Branche?",
 "rsvp_limit": 140,
 "date_in_series_pattern": false,
 "status": "upcoming",
 "time": 1573147800000,
 "local_date": "2019-11-07",
 "local_time": "18:30",
 "updated": 1571918409000,
 "utc_offset": 3600000,
 "waitlist_count": 0,
 "yes_rsvp_count": 17,
 "venue": {
 "id": 25852478,
 "name": "ThoughtWorks Munich ",
 "lat": 48.135372161865234,
 "lon": 11.613633155822754,
 "repinned": true,
 "address_1": "Bothestraße 11",
 "city": "München",
 "country": "de",
 "localized_country_name": "Germany"
 },
 "group": {
 "created": 1413448074000,
 "name": "ThoughtWorks Munich",
 "id": 17658472,
 "join_mode": "open",
 "lat": 48.13999938964844,
 "lon": 11.579999923706055,
 "urlname": "ThoughtWorks-Muenchen",
 "who": "Mitglieder",
 "localized_location": "München, Germany",
 "state": "",
 "country": "de",
 "region": "en_US",
 "timezone": "Europe/Berlin"
 },
 "link": "https://www.meetup.com/ThoughtWorks-Muenchen/events/265811041/",
 description: "<p>ThoughtWorks University - Wie starte ich meine Karriere in der IT-Branche?</p> <p>Details<br/>Der Weg zum IT-Job, der zu dir passt kann sehr vielfältig sein und häufig ist der Einstieg in die IT-Welt das schwierigste. ThoughtWorks hat ein eigenes Programm, das Berufseinsteiger und Absolventen auf diesem Weg unterstützt in Begleitung von Tech-Experten selbst zum Experte zu werden.</p> <p>Dein Abenteuer beginnt auf einem TWU-Campus in Indien oder China. Du warst noch nie dort? Wir helfen dir, dich vorzubereiten.<br/>Du verbringst...</p> ",
 "how_to_find_us": "The entrance is right next to the entrance of the big bike shop 'Stadler'. If you are standing in front of the entrance of Holiday Inn you have to go around the whole building to find our entrance.",
 "visibility": "public",
 "member_pay_fee": false
 },
 {
 "created": 1571482491000,
 "duration": 10800000,
 "id": "265793159",
 "name": "🎲 Game Night | games provided | 1 free drink",
 "date_in_series_pattern": false,
 "status": "upcoming",
 "time": 1573063200000,
 "local_date": "2019-11-06",
 "local_time": "19:00",
 "updated": 1571482574000,
 "utc_offset": 3600000,
 "waitlist_count": 0,
 "yes_rsvp_count": 16,
 "venue": {
 "id": 26609140,
 "name": "GoodWine Bar",
 "lat": 48.11894607543945,
 "lon": 11.571261405944824,
 "repinned": true,
 "address_1": "Sommerstraße 41",
 "address_2": "81543",
 "city": "München",
 "country": "de",
 "localized_country_name": "Germany"
 },
 "group": {
 "created": 1552581049000,
 "name": "Munich Mingle",
 "id": 31389319,
 "join_mode": "approval",
 "lat": 48.13999938964844,
 "lon": 11.579999923706055,
 "urlname": "munichmingle",
 "who": "members",
 "localized_location": "München, Germany",
 "state": "",
 "country": "de",
 "region": "en_US",
 "timezone": "Europe/Berlin"
 },
 "link": "https://www.meetup.com/munichmingle/events/265793159/",
 description: "<p>Secure your spot here: www.munichgamenight.eventbrite.com</p> <p>Meet internationals and locals in a fun and comfortable way while enjoying an evening of playing games.</p> <p>You don't need a team or to bring games. Games will be provided and the game masters are there to create teams, explain the rules and to get everyone up to speed so you can start enjoying the game ASAP and challenge your contestants.</p> <p>Games to play:<br/>🔸Cards Against Humanity: A party game for horrible people. One player asks a question from a black card, everyone else answers with their funniest white card.<br/>🔸Exploding Kittens: A highly-strategic, kitty-powered version of Russian Roulette.<br/>🔸You’ve Got Crabs: A game of deception, intrigue, friendship and secrecy.<br/>🔸Dixit: A lovingly illustrated game of creative guesswork, where your imagination unlocks the tale.<br/>🔸Conversation game cards: Take turns in drawing a card, each containing a thought-provoking question to get the conversation started.</p> <p>There will be more games available and you are also welcome to bring your own of course.</p> <p>Location:<br/>The Good Wine Bar is located near Kolumbusplatz, where you can enjoy a wide range of wines and a variety of drinks, tapas, cheese specialties and Flammkuchen. You will be welcomed by Lydia who will also be there to introduce you to other people.</p> <p>Tickets:<br/>www.munichgamenight.eventbrite.com<br/>- Regular: €5<br/>- Walk-in: €10 - Pay with Lydia at the event</p> <p>🔹Games provided<br/>🔹Game masters<br/>🔹Assigned area with tables to play in groups<br/>🔹Ticket includes 1 free drink</p> <p>This Meetup is an initiative of www.thecatchmaker.de</p> ",
 "how_to_find_us": "Lydia will be there to welcome you",
 "visibility": "public",
 "member_pay_fee": false
 },
 {
 "created": 1571213258000,
 "duration": 16200000,
 "id": "265707272",
 "name": "IoT and Smart Hardware Showcase 2019",
 "rsvp_limit": 200,
 "date_in_series_pattern": false,
 "status": "upcoming",
 "time": 1573144200000,
 "local_date": "2019-11-07",
 "local_time": "17:30",
 "updated": 1571213258000,
 "utc_offset": 3600000,
 "waitlist_count": 0,
 "yes_rsvp_count": 27,
 "group": {
 "created": 1328820641000,
 "name": "Internet of Things Munich",
 "id": 3265392,
 "join_mode": "open",
 "lat": 48.13999938964844,
 "lon": 11.579999923706055,
 "urlname": "IoTMunich",
 "who": "Sensemakers",
 "localized_location": "München, Germany",
 "state": "",
 "country": "de",
 "region": "en_US",
 "timezone": "Europe/Berlin"
 },
 "link": "https://www.meetup.com/IoTMunich/events/265707272/",
 description: "<p>This event is organized by the hardware pioneers</p> <p>REQUIRED TO ATTEND: Download a FREE TICKET here ...</p>",
 "visibility": "public",
 "member_pay_fee": false
 },
 {
 "created": 1550042729000,
 "duration": 10800000,
 "id": "258922181",
 "name": "108. JUG-München Treffen",
 "rsvp_limit": 30,
 "date_in_series_pattern": false,
 "status": "upcoming",
 "time": 1573664400000,
 "local_date": "2019-11-13",
 "local_time": "18:00",
 "updated": 1550042729000,
 "utc_offset": 3600000,
 "waitlist_count": 0,
 "yes_rsvp_count": 1,
 "venue": {
 "id": 25942014,
 "name": "Wirtshaus zum Isartal",
 "lat": 48.112571716308594,
 "lon": 11.553250312805176,
 "repinned": true,
 "address_1": "Brudermühlstrasse 2",
 "city": "München",
 "country": "de",
 "localized_country_name": "Germany"
 },
 "group": {
 "created": 1537211427000,
 "name": "Joomla User Group München",
 "id": 29852639,
 "join_mode": "open",
 "lat": 48.13999938964844,
 "lon": 11.579999923706055,
 "urlname": "Joomla-User-Group-Munchen",
 "who": "Mitglieder",
 "localized_location": "München, Germany",
 "state": "",
 "country": "de",
 "region": "en_US",
 "timezone": "Europe/Berlin"
 },
 "link": "https://www.meetup.com/Joomla-User-Group-Munchen/events/258922181/",
 description: "<p>Komm zum JUG-München Treffen und…</p> <p>- lerne nette Leute kennen, die sich mit Joomla! beschäftigen...</p>",
 visibility: "public",
 "member_pay_fee": false
 },
 {
 "created": 1550042767000,
 "duration": 10800000,
 "id": "258922189",
 "name": "109. JUG-München Treffen",
 "rsvp_limit": 30,
 "date_in_series_pattern": false,
 "status": "upcoming",
 "time": 1576083600000,
 "local_date": "2019-12-11",
 "local_time": "18:00",
 "updated": 1550042767000,
 "utc_offset": 3600000,
 "waitlist_count": 0,
 "yes_rsvp_count": 1,
 "venue": {
 "id": 25942014,
 "name": "Wirtshaus zum Isartal",
 "lat": 48.112571716308594,
 "lon": 11.553250312805176,
 "repinned": true,
 "address_1": "Brudermühlstrasse 2",
 "city": "München",
 "country": "de",
 "localized_country_name": "Germany"
 },
 "group": {
 "created": 1537211427000,
 "name": "Joomla User Group München",
 "id": 298343335263922,
 "join_mode": "open",
 "lat": 48.13999938964844,
 "lon": 11.579999923706055,
 "urlname": "Joomla-User-Group-Munchen",
 "who": "Mitglieder",
 "localized_location": "München, Germany",
 "state": "",
 "country": "de",
 "region": "en_US",
 "timezone": "Europe/Berlin"
 },
 "link": "https://www.meetup.com/Joomla-User-Group-Munchen/events/258922189/",
 "description": "<p>Komm zum JUG-München Treffen und…</p> <p>- lerne nette Leute kennen, die sich mit Joomla! beschäftigen<br/>- tausche Dich in lockerer Umgebung beim Stammtisch mit Gleichgesinnten aus<br/>- erhalte Hilfe zur Selbsthilfe und stelle Fragen an andere User und Profis<br/>- höre Dir Vorträge über und rund um Joomla! an oder halte selbst welche<br/>- nimm an Workshops teil oder vielleicht magst Du selbst einen veranstalten?<br/>- teile Dein Wissen und Deine Erfahrungen mit Joomla! oder Erweiterungen<br/>- erfahre aktuelle Informationen aus erster Hand rund um Joomla! oder Joomla!-Events<br/>- profitiere von unseren tollen Lokations und melde Dich heute noch zum Treffen an</p> ",
 "visibility": "public",
 "member_pay_fee": false
 },
 {
 "created": 1556806424000,
 "duration": 10800000,
 "id": "261105044",
 "name": "Teams UserGroup - Ignite Review",
 "rsvp_limit": 40,
 "date_in_series_pattern": false,
 "status": "upcoming",
 "time": 1574269200000,
 "local_date": "2019-11-20",
 "local_time": "18:00",
 "updated": 1571909707000,
 "utc_offset": 3600000,
 "waitlist_count": 4,
 "yes_rsvp_count": 47,
 "group": {
 "created": 1505650894000,
 "name": "Microsoft Teams Meetup Munich",
 "id": 25956792,
 "join_mode": "open",
 "lat": 48.13999938964844,
 "lon": 11.579999923706055,
 "urlname": "Microsoft-Teams-Meetup-Munich",
 "who": "Members",
 "localized_location": "München, Germany",
 "state": "",
 "country": "de",
 "region": "en_US",
 "timezone": "Europe/Berlin"
 },
 "link": "https://www.meetup.com/Microsoft-Teams-Meetup-Munich/events/261105044/",
 description: "<p>Hallo zusammen,</p> <p>so kurz nach der Microsoft Ignite in Orlando kann es nur ein Thema geben: Die größte Microsoft Veranstaltung der Welt.<br/>Holt Euch die wichtigsten Informationen von der Ignite direkt von den Experten die vor Ort waren.</p> <p>18:00 Uhr - Registrierung<br/>18:30 Uhr - Begrüßung<br/>18:35 Uhr - Ignite Review 1: Wir blicken zurück auf die Microsoft Ignite 2019 (Teil 1)<br/>19:10 Uhr - Pause mit Pizza und Getränken<br/>19:30 Uhr - Ignite Review 2: Wir blicken zurück auf die Microsoft Ignite 2019 (Teil 2)<br/>20:00 Uhr - Fragen und Antworten<br/>20:20 Uhr - Gemeinsame Gespräche und Networking</p> <p>Ihr wollt in einer anderen Stadt an dem MeetUp teilnehmen?</p> <p>Bochum:<br/><a href=\"https://www.meetup.com/de-DE/Microsoft-Teams-MeetUp-Bochum/events/261106864/\" class=\"linkified\">https://www.meetup.com/de-DE/Microsoft-Teams-MeetUp-Bochum/events/261106864/</a></p> <p>Hamburg:<br/><a href=\"https://www.meetup.com/de-DE/Skype-for-Business-User-Group-Hamburg/events/265897255/\" class=\"linkified\">https://www.meetup.com/de-DE/Skype-for-Business-User-Group-Hamburg/events/265897255/</a></p>",
 visibility: "public",
 "member_pay_fee": false
 },
 {
 "created": 1567432094000,
 "duration": 10800000,
 "id": "334",
 "name": "Mastering the Linux Command Line & Principles of Continuous Delivery and DevOps",
 "rsvp_limit": 120,
 "date_in_series_pattern": false,
 "status": "upcoming",
 "time": 1573581600000,
 "local_date": "2019-11-12",
 "local_time": "19:00",
 "updated": 1570554830000,
 "utc_offset": 3600000,
 "waitlist_count": 8,
 "yes_rsvp_count": 132,
 "venue": {
 "id": 26112492,
 "name": "Google",
 "lat": 48.143035888671875,
 "lon": 11.541084289550781,
 "repinned": true,
 "address_1": "Erika-Mann-Straße 33",
 "city": "München",
 "country": "de",
 "localized_country_name": "Germany"
 },
 "group": {
 "created": 1565272185000,
 "name": "OpenValue München",
 "id": 32563109,
 "join_mode": "open",
 "lat": 48.13999938964844,
 "lon": 11.579999923706055,
 "urlname": "OpenValueMuenchen",
 "who": "Members",
 "localized_location": "München, Germany",
 "state": "",
 "country": "de",
 "region": "en_US",
 "timezone": "Europe/Berlin"
 },
 "link": "https://www.meetup.com/OpenValueMuenchen/events/264495082/",
 "description": "<p>Bert Jan Schrijver - Two topics</p> <p>Agenda</p> <p>19:00 Networking<br/>19:30 First topic (see below)<br/>20:30 Break<br/>20:45 Second topic (see below)</p> <p>1) Mastering the Linux command line</p> <p>As a developer, you often have to deal with Linux servers. Troubleshooting, digging through logs, editing configuration files, you name it. If you're used to working with Windows or OSX GUI's, the Linux terminal might appear fairly basic and difficult to use.<br/>But, with some basic background knowledge and a small set of terminal commands in your toolbox, it can actually be extremely powerful and loads of fun!<br/>In this session, I'll explain the concepts behind the Linux command line and I'll demo loads of useful stuff. You'll learn how to quickly navigate, find files, examine and search through logs, how to investigate a system under load, a bit of shell scripting, ssh tunneling and more!<br/>At the end of this session, you'll have the chance to throw your own problems and use cases at me - I'll come up with solutions on the spot. Bring your own problems ;-)<br/>This talk takes places entirely in the command line. No slides, no IDE, just a plain terminal window. After this session, you'll be on your way to master the Linux command line yourself!</p> <p>2) Better software, faster: Principles of Continuous Delivery and DevOps</p> <p>The Wall Street Journal already mentioned it in 2011: “Software is eating the world.” Nowadays, every company is an IT company. Product owners and other business representatives seeing their competitors release new features to end users every day are demanding the same from their own software teams. How do you measure up to this heavy pressure as an IT organization? How do you quickly make changes to software systems in fast-paced environments without losing your grip on quality? How do you build and test software in such a way that it's always in a releasable state? This session explains the principles of continuous delivery and DevOps. You’ll leave with enough insights into how and where to get started yourself.</p> <p>About the Speaker: Bert Jan Schrijver is CTO at OpenValue and focuses on Java, Continuous Delivery and DevOps. Bert Jan is a Java Champion, JavaOne Rock Star speaker, Duke's Choice Award winner and leads NLJUG, the Dutch Java User Group. He loves to share his experience by speaking at conferences, writing for the Dutch Java magazine and helping out Devoxx4Kids with teaching kids how to code. Bert Jan is easily reachable on Twitter at @bjschrijver.</p> ",
 "visibility": "public",
 "pro_is_email_shared": false,
 "member_pay_fee": false
 },
 {
 "created": 1570631402000,
 "duration": 1800000,
 "id": "265531605",
 "name": "Webinar: Build the Right Things by Voyagent, Inc. Founder",
 "date_in_series_pattern": false,
 "status": "upcoming",
 "time": 1573068600000,
 "local_date": "2019-11-06",
 "local_time": "20:30",
 "updated": 1570631601000,
 "utc_offset": 3600000,
 "waitlist_count": 0,
 "yes_rsvp_count": 11,
 "group": {
 "created": 1570531441000,
 "name": "Product School Munich",
 "id": 32863959,
 "join_mode": "open",
 "lat": 48.13999938964844,
 "lon": 11.579999923706055,
 "urlname": "Product-School-Munich",
 "who": "Members",
 "localized_location": "München, Germany",
 "state": "",
 "country": "de",
 "region": "en_US",
 "timezone": "Europe/Berlin"
 },
 "link": "https://www.meetup.com/Product-School-Munich/events/265531605/",
 description: "<p>***RSVP on EventBrite: <a href=\"https://prdct.school/2Mp55jL\" class=\"linkified\">https://prdct.school/2Mp55jL</a> ***</p> <p>*** DISCLAIMER: This event is ONLINE ***</p> <p>Too many startup founders begin with an idea and jump straight into execution without validating their idea in the market early and often. When they release their product, it doesn't resonate with their target users. As the founders continue to pivot in search of product-market fit, they burn cash until they eventually run out. In this session, Eric will show you the philosophy, frameworks, and tools you can use to drastically increase your chance of success by decreasing the cost of development and ensuring you're building a product that solves an urgent need.</p> <p>Main takeaways:<br/>- How to create a user-centered culture and design process<br/>- How to leverage data and analytics to drive product decisions<br/>- How to tightly integrate the product leaders, engineers, and customers<br/>- How to validate product/feature ideas quickly and with the lowest cost<br/>- How to create an idea meritocracy</p> <p>Meet the Speaker: Eric Weiss</p> <p>With almost 15 years of experience building technology products in a variety of roles, Eric can transform companies into streamlined and effective organizations with a shared purpose. He is currently a Founder at Voyagent and at Full Cycle Product Development.</p> <p>Get Eric's book \"Build the Right Things: How to Design and Build a Product People Will Love\" here (<a href=\"https://www.amazon.com.mx/Build-Right-Things-Product-English-ebook/dp/B07XXHH5DS\" class=\"linkified\">https://www.amazon.com.mx/Build-Right-Things-Product-English-ebook/dp/B07XXHH5DS</a>)</p> <p>View Speaker's Full Profile (<a href=\"https://prod.school/2OvXVwI\" class=\"linkified\">https://prod.school/2OvXVwI</a>)</p> <p>Get the FREE Product Book here (<a href=\"https://prdct.school/2CMSqF1\" class=\"linkified\">https://prdct.school/2CMSqF1</a>)</p> <p>Get Your Tickets (<a href=\"https://prdct.school/2Mp55jL\" class=\"linkified\">https://prdct.school/2Mp55jL</a>)</p> <p>*Entrance not guaranteed without valid ticket from Eventbrite</p>",
 visibility: "public",
 "member_pay_fee": false
 },
 {
 "created": 1543406706000,
 "duration": 32400000,
 "id": "256774760222",
 "name": "Hack&Jump - Munich's bus tour for coders & developers",
 "date_in_series_pattern": false,
 "status": "upcoming",
 "time": 1573124400000,
 "local_date": "2019-11-07",
 "local_time": "12:00",
 "updated": 1566905829000,
 "utc_offset": 3600000,
 "waitlist_count": 0,
 "yes_rsvp_count": 34,
 "venue": {
 "id": 26120186,
 "name": "HANS IM GLÜCK Burgergrill & Bar",
 "lat": 48.12040710449219,
 "lon": 11.603134155273438,
 "repinned": false,
 "address_1": "St.-Martin-Straße 57",
 "city": "München",
 "country": "de",
 "localized_country_name": "Germany"
 },
 "group": {
 "created": 1501244830000,
 "name": "Tech_Hub München",
 "id": 25186228,
 "join_mode": "open",
 "lat": 48.13999938964844,
 "lon": 11.579999923706055,
 "urlname": "Tech_Hub-Munchen",
 "who": "Members",
 "localized_location": "München, Germany",
 "state": "",
 "country": "de",
 "region": "en_US",
 "timezone": "Europe/Berlin"
 },
 "link": "https://www.meetup.com/Tech_Hub-Munchen/events/256774760/",
 description: "<p>Join our IT-Job-Shuttle to the digital economy of Munich. During the tour, you can look behind the scenes of high-tech companies and have valuable contacts to IT-professionals of the participating companies. Catering will be provided all day. To the end of the day we have a Get-Together and serve good food and free beer.</p> <p>Steig ein in den IT-Job-Shuttle durch die Münchner Digitalwirtschaft. Während der mehrstündigen Tour kannst Du hinter die Kulissen von Hightech-Unternehmen schauen und wertvolle Kontakte zu Fachleuten und Personalern in den beteiligten Unternehmen knüpfen. Für die Verpflegung zwischendurch ist bestens gesorgt. Zum Ausklang des Abends erwarten Dich dann nochmal gutes Essen und Freibier.</p> <p>#hightech #kaffeefahrt #ITjobs</p> <p>Join us: www.hack-and-jump.de and please REGISTER HERE <a href=\"https://www.eventbrite.de/e/hackjump-der-it-job-shuttle-in-munchen-2019-tickets-50166116204\" class=\"linkified\">https://www.eventbrite.de/e/hackjump-der-it-job-shuttle-in-munchen-2019-tickets-50166116204</a> - if you don't have a ticket jet - please register!</p>",
 visibility: "public",
 "member_pay_fee": false
 },
 {
 "created": 1571223250000,
 "duration": 7200000,
 "id": "265709123",
 "name": "Best Startups from Hamburg - Pitchnight#1 - München",
 "rsvp_limit": 200,
 "date_in_series_pattern": false,
 "status": "upcoming",
 "time": 1579111200000,
 "local_date": "2020-01-15",
 "local_time": "19:00",
 "updated": 1571770971000,
 "utc_offset": 3600000,
 "waitlist_count": 0,
 "yes_rsvp_count": 18,
 "group": {
 "created": 1571221326000,
 "name": "Wow Yes Startups - München",
 "id": 32898396,
 "join_mode": "open",
 "lat": 48.13999938964844,
 "lon": 11.579999923706055,
 "urlname": "wow-yes-Startups-Munchen",
 "who": "Mitglieder",
 "localized_location": "München, Germany",
 "state": "",
 "country": "de",
 "region": "en_US",
 "timezone": "Europe/Berlin"
 },
 "link": "https://www.meetup.com/wow-yes-Startups-Munchen/events/265709123/",
 description: "<p>HAMBURG’S BEST STARTUPS VISIT MUNICH</p> <p>we connect startups with matching investors.</p> <p>Wir laden alle Startups, Investoren und sonstige Interessierte herzlich ein, an diesem Abend dabei zu sein!</p> <p>Die fünf Gewinner unserer Hamburger Startup Competition pitchen ihr Business vor interessierten Investoren und Publikum in München. Wir freuen uns auf einen tollen Abend in entspannter Atmosphäre!</p> <p>Ablauf:</p> <p>Beginn um 19:00 Uhr<br/>Pitch eines erfolgreichen, lokalen Startups<br/>5 Pitches der besten Hamburger Startups<br/>Q&amp;A mit Münchner Investoren und Startup Community<br/>Lokale Jury wählt das Gewinnerstartup des Abends<br/>Networking an der Bar<br/>Ende um 22:00 Uhr</p> <p>Alle Infos zu uns und unseren Events findest Du hier: <a href=\"https://www.meetup.com/de-DE/wow-yes-Startups-Munchen/\" class=\"linkified\">https://www.meetup.com/de-DE/wow-yes-Startups-Munchen/</a></p> <p>******************************************</p> <p>ENGLISH</p> <p>You are a startup, investor or just curious about the startup community? Then you are cordially invited to meet Hamburg’s best startups in Munich!</p> <p>The five winners of our Hamburg Startup Competition will pitch their business in front of interested investors and the public in Munich. We are looking forward to a great evening in a relaxed atmosphere!</p> <p>Agenda:</p> <p>Start at 7 p.m.<br/>Pitch of a successful, local startup<br/>5 pitches from Hamburg’s best startups<br/>Q&amp;A with Munich investors and startup community<br/>Local jury selects the winner startup of the evening<br/>Networking at the bar<br/>End at 10 p.m.</p> <p>You can find all information about us and our events here: <a href=\"https://www.meetup.com/de-DE/wow-yes-Startups-Munchen/\" class=\"linkified\">https://www.meetup.com/de-DE/wow-yes-Startups-Munchen/</a></p> ",
 visibility: "public",
 "member_pay_fee": false
 },
 {
 "created": 1571083854000,
 "duration": 7200000,
 "id": "265668928",
 "name": "Abendworkshop - Inner-Leadership: Ein innovativer Ansatz für Transformation",
 "rsvp_limit": 60,
 "date_in_series_pattern": false,
 "status": "upcoming",
 "time": 1572285600000,
 "local_date": "2019-10-28",
 "local_time": "19:00",
 "updated": 1571854601000,
 "utc_offset": 3600000,
 "waitlist_count": 5,
 "yes_rsvp_count": 60,
 "venue": {
 "id": 25615449,
 "name": "Henley Business School Germany",
 "lat": 48.13741683959961,
 "lon": 11.58404541015625,
 "repinned": true,
 "address_1": "Maximilianstraße 40",
 "city": "München",
 "country": "de",
 "localized_country_name": "Germany"
 },
 "group": {
 "created": 1510684582000,
 "name": "Leadership Events - München",
 "id": 26598849,
 "join_mode": "open",
 "lat": 48.13999938964844,
 "lon": 11.579999923706055,
 "urlname": "Leadership-Events-Munchen",
 "who": "Mitglieder",
 "localized_location": "München, Germany",
 "state": "",
 "country": "de",
 "region": "en_US",
 "timezone": "Europe/Berlin"
 },
 "link": "https://www.meetup.com/Leadership-Events-Munchen/events/265668928/",
 "description": "<p>Inner-Leadership ist der grundlegendste Ansatz für jede Transformation und ein erfülltes und erfolgreiches Leben. Das Bewusstsein für den eigenen Umgang mit sich selbst, ist unser langfristiges Kapital - persönlich, unternehmerisch und gesellschaftlich. Unsere psychologische und physische Fitness, mentale Resilienz und emotionale Intelligenz sind die Voraussetzung dafür, unser höchstes Potenzial zu entfalten und zu leben.</p> <p>Unternehmen, die dies neben den persönlichen Werten und dem individuellen Wachstum ihrer Mitarbeiter in den Vordergrund stellen, folgen dem Zeitgeist. Um die beste Version ihrer Selbst zu werden, unterstützen sie ihre Mitarbeiter in der Entwicklung ihres höchsten Potentials. Inner-Leadership bricht einschränkende, nicht hilfreiche Gewohnheiten, Überzeugungen und Verhaltensweisen auf und ebnet den Weg für eine nachhaltige und messbare Transformationsenergie - im innen und außen.</p> <p>In diesem Monday@Henley gibt Henley Alumna Dr. Eva Gattnar Einblicke, wie dies gelingen kann. Durch Nutzung von innovativen Methoden können wir ein Bewusstsein für den eigenen Umgang mit uns selbst schaffen, um unsere innere Fitness, mentale und emotionale Stärke für mehr Erfüllung, mehr Belastbarkeit und mehr Lebensqualität nachhaltig, mit messbarem Erfolg, aufzubauen. Actualize yourself and become your highest version!</p> <p>Wir beginnen wie immer mit Networking um 18.30 Uhr und der Workshop startet um 19 Uhr; das Ende ist für 21 Uhr geplant, gefolgt von einer halben Stunde Networking zum Ausklang.</p> ",
 "how_to_find_us": "Der Eingang befindet sich am Thomas-Wimmer Ring, Ecke Hildegardstraße (///gams.aufheben.alge). Dort im 2. Stock.",
 "visibility": "public",
 "member_pay_fee": false
 },
 {
 "local_time": "19:00",
 "local_date": "2019-10-31",
 "link": "https://www.meetup.com/Djembe-and-Percussion-Fun-Munchen/events/265750801/",
 "visibility": "public_limited",
 "group": {
 "created": 1376421848000,
 "name": "Djembe and Percussion Fun Muenchen",
 "id": 9795322,
 "join_mode": "approval",
 "lat": 48.13999938964844,
 "lon": 11.579999923706055,
 "urlname": "Djembe-and-Percussion-Fun-Munchen",
 "who": "Munich Percussionists",
 "localized_location": "München, Germany",
 "state": "",
 "country": "de",
 "region": "en_US",
 "timezone": "Europe/Berlin"
 },
 "waitlist_count": 0,
 "yes_rsvp_count": 3,
 "duration": 7200000,
 "time": 1572544800000,
 "utc_offset": 3600000,
 "name": "Neue Regeln für neue Mitglieder",
 "id": "265750801333"
 },
 {
 "created": 1569143472000,
 "duration": 7200000,
 "id": "265062898",
 "name": "Elementor MeetUp München - November 2019",
 "date_in_series_pattern": false,
 "status": "upcoming",
 "time": 1574186400000,
 "local_date": "2019-11-19",
 "local_time": "19:00",
 "updated": 1570709361000,
 "utc_offset": 3600000,
 "waitlist_count": 0,
 "yes_rsvp_count": 5,
 "venue": {
 "id": 26638286,
 "name": "Heinrich Marketing GmbH",
 "lat": 48.14986038208008,
 "lon": 11.549469947814941,
 "repinned": true,
 "address_1": "Nymphenburger Str. 58",
 "address_2": "Hinterhof, rechts",
 "city": "München",
 "country": "de",
 "localized_country_name": "Germany"
 },
 "group": {
 "created": 1549966106000,
 "name": "Elementor München",
 "id": 31146435,
 "join_mode": "open",
 "lat": 48.13999938964844,
 "lon": 11.579999923706055,
 "urlname": "Muenchen-Elementor-Meetup",
 "who": "Mitglieder",
 "localized_location": "München, Germany",
 "state": "",
 "country": "de",
 "region": "en_US",
 "timezone": "Europe/Berlin"
 },
 "link": "https://www.meetup.com/Muenchen-Elementor-Meetup/events/265062898/",
 "description": "<p>Einzelheiten werden noch bekannt gegeben</p> ",
 "visibility": "public",
 "pro_is_email_shared": false,
 "member_pay_fee": false
 },
 {
 "created": 1571559775000,
 "id": "265810514",
 "name": "Halloween",
 "date_in_series_pattern": false,
 "status": "upcoming",
 "time": 1572552000000,
 "local_date": "2019-10-31",
 "local_time": "21:00",
 "updated": 1571559833000,
 "utc_offset": 3600000,
 "waitlist_count": 0,
 "yes_rsvp_count": 12,
 "venue": {
 "id": 26691826,
 "name": "upside east",
 "lat": 48.12247848510742,
 "lon": 11.606674194335938,
 "repinned": false,
 "address_1": "Rosenheimer Str. 145 D",
 "city": "München",
 "country": "DE",
 "localized_country_name": "Germany"
 },
 "group": {
 "created": 1570119258000,
 "name": "For active Singles",
 "id": 32843927,
 "join_mode": "open",
 "lat": 48.13999938964844,
 "lon": 11.579999923706055,
 "urlname": "for-those-who-hates-being-alone",
 "who": "Mitglieder",
 "localized_location": "München, Germany",
 "state": "",
 "country": "de",
 "region": "en_US",
 "timezone": "Europe/Berlin"
 },
 "link": "https://www.meetup.com/for-those-who-hates-being-alone/events/265810514/",
 "description": "<p>Hey Guys,<br/>Let's celebrate Halloween at upside east (Ostbahnhof) It's a nice location with a rooftop bar. I'll be there at 9pm and will wait for you inside the club</p> ",
 "visibility": "public",
 "member_pay_fee": false
 },
 {
 "created": 1561546757000,
 "duration": 7200000,
 "id": "26263743422",
 "name": "#NoEstimates-How to improve software development predictability & profitability",
 "rsvp_limit": 140,
 "date_in_series_pattern": false,
 "status": "upcoming",
 "time": 1573493400000,
 "local_date": "2019-11-11",
 "local_time": "18:30",
 "updated": 1571905670000,
 "utc_offset": 3600000,
 "waitlist_count": 0,
 "yes_rsvp_count": 125,
 "venue": {
 "id": 25852478,
 "name": "ThoughtWorks Munich ",
 "lat": 48.135372161865234,
 "lon": 11.613633155822754,
 "repinned": true,
 "address_1": "Bothestraße 11",
 "city": "München",
 "country": "de",
 "localized_country_name": "Germany"
 },
 "group": {
 "created": 1413448074000,
 "name": "ThoughtWorks Munich",
 "id": 17658472,
 "join_mode": "open",
 "lat": 48.13999938964844,
 "lon": 11.579999923706055,
 "urlname": "ThoughtWorks-Muenchen",
 "who": "Mitglieder",
 "localized_location": "München, Germany",
 "state": "",
 "country": "de",
 "region": "en_US",
 "timezone": "Europe/Berlin"
 },
 "link": "https://www.meetup.com/ThoughtWorks-Muenchen/events/262637434/",
 description: "<p>TW hosts: #NoEstimates-How to improve software development predictability and profitability by focusing on what matters</p> <p>In this Meetup, your basic assumptions about the role of estimation will be challenged.</p> <p>We will share how to be sure to deliver on time, no matter whether you use estimates or not! You already know that many things go wrong, no matter how well you try to estimate. People are assigned 10% to a project, or work in 4 different projects at the same time. Managers fight to get experts assigned to their projects, and that creates unforeseen delays and problems. Not to mention illnesses, people changing jobs, promotions, etc. Forget all of that. You can account for all of those “unexpected” events. And you can do it without estimates! Yes, without estimates!</p> <p>We’ll look into cases where estimation is the core failure pattern in projects, and why they happen. We’ll look into how to overcome those failure patterns, and help you know what is the real progress in your project without asking all the teams to sit down and endlessly discuss what the size of a story is.</p> <p>[ Bonus: If you are interested in learning the details of how to do it, Vasco Duarte is organizing a 1-day workshop where we dive deeper into the techniques and tools that allow you to put #NoEstimates into action and save your project! To know more about the full-day #NoEstimates Workshop (November 12th) &amp; Product Owner Success Toolkit Workshop (November 11th), go here: <a href=\"https://oikosofyseries.com/workshops-by-vasco-duarte-product-owner-success-toolkit-and-noestimates\" class=\"linkified\">https://oikosofyseries.com/workshops-by-vasco-duarte-product-owner-success-toolkit-and-noestimates</a> ]</p> <p>About the Presenter<br/># Vasco Duarte, Author of #NoEstimates, Speaker &amp; Co-Founder at Oikosofy<br/>Product Manager, Scrum Master, Project Manager, Director, Agile Coach - only some of the roles that he has taken in software development organizations. Having worked in the software industry since 1997, and Agile practitioner since 2004. He has worked in small, medium and large software organizations as an Agile Coach or leader in agile adoption at those organizations. He was one of the leaders of Agile methods and Agile culture adoption at Avira, Nokia, F-Secure.</p> <p>AGENDA:<br/>18:30 Snacks, drinks and mingle<br/>19:00 Talk and questions<br/>20:00 More questions, drinks and mingle</p> <p>SNACKS:<br/>As always we are offering various snacks and, beer and soft drinks. No full meal, but at least something to eat.</p>",
 how_to_find_us: "The entrance is right next to the entrance of the big bike shop “Stadler”. If you are standing in front of the entrance of Holiday Inn you have to go around the whole building to find our entrance.",
 "visibility": "public",
 "member_pay_fee": false
 },
 {
 "created": 1548145714000,
 "duration": 7200000,
 "id": "258288773222",
 "name": "Wie Sie den Mehrwert eines PMOs sichtbar machen können",
 "date_in_series_pattern": false,
 "status": "upcoming",
 "time": 1573754400000,
 "local_date": "2019-11-14",
 "local_time": "19:00",
 "updated": 1548145714000,
 "utc_offset": 3600000,
 "waitlist_count": 0,
 "yes_rsvp_count": 9,
 "venue": {
 "id": 25697058,
 "name": "Schuhbecks Orlando Lounge ",
 "lat": 48.13831329345703,
 "lon": 11.580145835876465,
 "repinned": true,
 "address_1": "Platzl 4  ",
 "city": "München",
 "country": "de",
 "localized_country_name": "Germany"
 },
 "group": {
 "created": 1516184773000,
 "name": "Project Management Office Stammtisch München - PMO-Meetup",
 "id": 27185043,
 "join_mode": "open",
 "lat": 48.13999938964844,
 "lon": 11.579999923706055,
 "urlname": "Project-Management-Office-Stammtisch-Munchen-PMO-Meetup",
 "who": "Members",
 "localized_location": "München, Germany",
 "state": "",
 "country": "de",
 "region": "en_US",
 "timezone": "Europe/Berlin"
 },
 link: "https://www.meetup.com/Project-Management-Office-Stammtisch-Munchen-PMO-Meetup/events/258288773/",
 description: "<p>Die Arbeit eines PMOs ist häufig von Widerständen begleitet. Ein PMO kostet Geld, kann für manche Kollegen lästig sein und auch als überflüssiger Overhead gelten. Im Rahmen einer Verschlankung könnte es daher schnell dem Rotstift zum Opfer fallen. Umso wichtiger ist es für die Verantwortlichen, den Mehrwert fundiert darstellen zu können. Welche Möglichkeiten es dafür gibt, darum geht es an diesem Abend.</p> <p>Nach einer kurzen Einführung sammeln die Teilnehmer in Arbeitsgruppen Ideen. Diese werden dann gemeinsam präsentiert und diskutiert. Tauschen Sie sich intensiv mit Ihren Peers aus und erweitern Sie Ihr Netzwerk. Jetzt gleich kostenlos anmelden.</p> <p>Achtung, die Plätze sind begrenzt. Bitte unbedingt vorher kostenlos anmelden unter <a href=\"https://www.theprojectgroup.com/pmo-stammtisch\" class=\"linkified\">https://www.theprojectgroup.com/pmo-stammtisch</a></p> <p>Und noch was: Werfen Sie unbedingt auch einen Blick auf das Programm unserer kostenlosen Webinare. Das Programm wird laufend aktualisiert: <a href=\"https://www.theprojectgroup.com/webinar\" class=\"linkified\">https://www.theprojectgroup.com/webinar</a></p>",
 how_to_find_us: "Bitte unbedingt vorher kostenlos anmelden unter https://www.theprojectgroup.com/pmo-stammtisch",
 "visibility": "public",
 "member_pay_fee": false
 },
 {
   created: 1371224928000,
   id: "drpzdgyzpbrb333",
   name: "Ruby User Group Meetup",
   date_in_series_pattern: false,
   status: "upcoming",
   time: 1573668000000,
   local_date: "2019-11-13",
   local_time: "19:00",
   updated: 1507810525000,
   utc_offset: 3600000,
   waitlist_count: 0,
   yes_rsvp_count: 3,
   group: {
   created: 1370808069000,
   name: "Munich Rubyshift, Ruby User Group",
   "id": 8851722,
   "join_mode": "open",
   "lat": 48.13999938964844,
   "lon": 11.579999923706055,
   "urlname": "Munich-Rubyshift-Ruby-User-Group",
   "who": "Rubyists",
   "localized_location": "München, Germany",
   "state": "",
   "country": "de",
   "region": "en_US",
   "timezone": "Europe/Berlin"
   },
   "link": "https://www.meetup.com/Munich-Rubyshift-Ruby-User-Group/events/drpzdgyzpbrb/",
   "description": "<p>We're actively searching for speakers! Want to become one? Ping us!</p> ",
   "visibility": "public",
   "member_pay_fee": false
   },
   {
   "created": 1571344936000,
   "duration": 7200000,
   "id": "2657514882",
   "name": "Winter is coming - Serverless is prepared",
   "date_in_series_pattern": false,
   "status": "upcoming",
   "time": 1573061400000,
   "local_date": "2019-11-06",
   "local_time": "18:30",
   "updated": 1571345988000,
   "utc_offset": 3600000,
   "waitlist_count": 0,
   "yes_rsvp_count": 80,
   "venue": {
   "id": 2621945333,
   "name": "Oskar-von-Miller-Ring 20",
   "lat": 48.1448974609375,
   "lon": 11.57638931274414,
   "repinned": true,
   "address_1": "Oskar-von-Miller-Ring 20",
   "city": "München",
   "country": "de",
   "localized_country_name": "Germany"
   },
   "group": {
   "created": 1473068565000,
   "name": "Serverless Munich",
   "id": 203896642,
   "join_mode": "open",
   "lat": 48.13999938964844,
   "lon": 11.579999923706055,
   "urlname": "Serverless-Munich",
   "who": "Members",
   "localized_location": "München, Germany",
   "state": "",
   "country": "de",
   "region": "en_US",
   "timezone": "Europe/Berlin"
   },
   link: "https://www.meetup.com/Serverless-Munich/events/265751488/",
   description: '<p>This season we found a small cosy vendor who will give us shelter in front of the fireplace...</p>',
   how_to_find_us: "AWS Office, 1st Floor",
   "visibility": "public",
   "member_pay_fee": false
   },
   {
   "created": 1564472388000,
   "duration": 30600000,
   "id": "2635772052232",
   "name": "Global Day of Coderetreat @ ThoughtWorks Munich",
   "rsvp_limit": 70,
   "date_in_series_pattern": false,
   "status": "upcoming",
   "time": 1573889400000,
   "local_date": "2019-11-16",
   "local_time": "08:30",
   "rsvp_open_offset": "PT673H",
   "updated": 1564748617000,
   "utc_offset": 3600000,
   "waitlist_count": 0,
   "yes_rsvp_count": 38,
   "venue": {
   "id": 2585247866,
   "name": "ThoughtWorks Munich ",
   "lat": 48.135372161865234,
   "lon": 11.613633155822754,
   "repinned": true,
   "address_1": "Bothestraße 11",
   "city": "München",
   "country": "de",
   "localized_country_name": "Germany"
   },
   "group": {
   "created": 1413448074000,
   "name": "ThoughtWorks Munich",
   "id": 176584721,
   "join_mode": "open",
   "lat": 48.13999938964844,
   "lon": 11.579999923706055,
   "urlname": "ThoughtWorks-Muenchen",
   "who": "Mitglieder",
   "localized_location": "München, Germany",
   "state": "",
   "country": "de",
   "region": "en_US",
   "timezone": "Europe/Berlin"
   },
   "link": "https://www.meetup.com/ThoughtWorks-Muenchen/events/263577205/",
   description: "<p>Welcome to the Global Day of Coderetreat in Munich on Saturday November 16th at ThoughtWorks Munich!</p> <p>On Saturday, November 16th...</p>",
   visibility: "public",
   "member_pay_fee": false
   },
   {
   "created": 1571209775000,
   "duration": 9000000,
   "id": "2657066381",
   "name": "Evening Workshop on: 'Developing a Coaching Culture in your organisation'",
   "rsvp_limit": 50,
   "date_in_series_pattern": false,
   "status": "upcoming",
   "time": 1573752600000,
   "local_date": "2019-11-14",
   "local_time": "18:30",
   "updated": 1571209801000,
   "utc_offset": 3600000,
   "waitlist_count": 2,
   "yes_rsvp_count": 50,
   "venue": {
   "id": 256154491,
   "name": "Henley Business School Germany",
   "lat": 48.13788604736328,
   "lon": 11.583979606628418,
   "repinned": true,
   "address_1": "Maximilianstraße 40",
   "city": "München",
   "country": "de",
   "localized_country_name": "Germany"
   },
   "group": {
   "created": 1510684582000,
   "name": "Leadership Events - München",
   "id": 2659884911,
   "join_mode": "open",
   "lat": 48.13999938964844,
   "lon": 11.579999923706055,
   "urlname": "Leadership-Events-Munchen",
   "who": "Mitglieder",
   "localized_location": "München, Germany",
   "state": "",
   "country": "de",
   "region": "en_US",
   "timezone": "Europe/Berlin"
   },
   link: "https://www.meetup.com/Leadership-Events-Munchen/events/265706638/",
   description: "<p>Many organisations are discussing how they can develop a coaching culture. But what does this mean in practice?...</p>",
   What3words: "///gams.aufheben.alge",
   "visibility": "public",
   "member_pay_fee": false
   },
   {
   "created": 1571563126000,
   "duration": 7200000,
   "id": "26581104112",
   "name": "ThoughtWorks University - Wie starte ich meine Karriere in der IT-Branche?",
   "rsvp_limit": 140,
   "date_in_series_pattern": false,
   "status": "upcoming",
   "time": 1573147800000,
   "local_date": "2019-11-07",
   "local_time": "18:30",
   "updated": 1571918409000,
   "utc_offset": 3600000,
   "waitlist_count": 0,
   "yes_rsvp_count": 17,
   "venue": {
   "id": 2585247822,
   "name": "ThoughtWorks Munich ",
   "lat": 48.135372161865234,
   "lon": 11.613633155822754,
   "repinned": true,
   "address_1": "Bothestraße 11",
   "city": "München",
   "country": "de",
   "localized_country_name": "Germany"
   },
   "group": {
   "created": 1413448074000,
   "name": "ThoughtWorks Munich",
   "id": 17658472444,
   "join_mode": "open",
   "lat": 48.13999938964844,
   "lon": 11.579999923706055,
   "urlname": "ThoughtWorks-Muenchen",
   "who": "Mitglieder",
   "localized_location": "München, Germany",
   "state": "",
   "country": "de",
   "region": "en_US",
   "timezone": "Europe/Berlin"
   },
   "link": "https://www.meetup.com/ThoughtWorks-Muenchen/events/265811041/",
   description: "<p>ThoughtWorks University - Wie starte ich meine Karriere in der IT-Branche?</p> <p>Details<br/>Der Weg zum IT-Job, der zu dir passt kann sehr vielfältig sein und häufig ist der Einstieg in die IT-Welt das schwierigste. ThoughtWorks hat ein eigenes Programm, das Berufseinsteiger und Absolventen auf diesem Weg unterstützt in Begleitung von Tech-Experten selbst zum Experte zu werden.</p> <p>Dein Abenteuer beginnt auf einem TWU-Campus in Indien oder China. Du warst noch nie dort? Wir helfen dir, dich vorzubereiten.<br/>Du verbringst...</p> ",
   "how_to_find_us": "The entrance is right next to the entrance of the big bike shop 'Stadler'. If you are standing in front of the entrance of Holiday Inn you have to go around the whole building to find our entrance.",
   "visibility": "public",
   "member_pay_fee": false
   },
   {
   "created": 1571482491000,
   "duration": 10800000,
   "id": "2657931592",
   "name": "🎲 Game Night | games provided | 1 free drink",
   "date_in_series_pattern": false,
   "status": "upcoming",
   "time": 1573063200000,
   "local_date": "2019-11-06",
   "local_time": "19:00",
   "updated": 1571482574000,
   "utc_offset": 3600000,
   "waitlist_count": 0,
   "yes_rsvp_count": 16,
   "venue": {
   "id": 2660914022,
   "name": "GoodWine Bar",
   "lat": 48.11894607543945,
   "lon": 11.571261405944824,
   "repinned": true,
   "address_1": "Sommerstraße 41",
   "address_2": "81543",
   "city": "München",
   "country": "de",
   "localized_country_name": "Germany"
   },
   "group": {
   "created": 1552581049000,
   "name": "Munich Mingle",
   "id": 31389319,
   "join_mode": "approval",
   "lat": 48.13999938964844,
   "lon": 11.579999923706055,
   "urlname": "munichmingle",
   "who": "members",
   "localized_location": "München, Germany",
   "state": "",
   "country": "de",
   "region": "en_US",
   "timezone": "Europe/Berlin"
   },
   "link": "https://www.meetup.com/munichmingle/events/265793159/",
   description: "<p>Secure your spot here: www.munichgamenight.eventbrite.com</p> <p>Meet internationals and locals in a fun and comfortable way while enjoying an evening of playing games.</p> <p>You don't need a team or to bring games. Games will be provided and the game masters are there to create teams, explain the rules and to get everyone up to speed so you can start enjoying the game ASAP and challenge your contestants.</p> <p>Games to play:<br/>🔸Cards Against Humanity: A party game for horrible people. One player asks a question from a black card, everyone else answers with their funniest white card.<br/>🔸Exploding Kittens: A highly-strategic, kitty-powered version of Russian Roulette.<br/>🔸You’ve Got Crabs: A game of deception, intrigue, friendship and secrecy.<br/>🔸Dixit: A lovingly illustrated game of creative guesswork, where your imagination unlocks the tale.<br/>🔸Conversation game cards: Take turns in drawing a card, each containing a thought-provoking question to get the conversation started.</p> <p>There will be more games available and you are also welcome to bring your own of course.</p> <p>Location:<br/>The Good Wine Bar is located near Kolumbusplatz, where you can enjoy a wide range of wines and a variety of drinks, tapas, cheese specialties and Flammkuchen. You will be welcomed by Lydia who will also be there to introduce you to other people.</p> <p>Tickets:<br/>www.munichgamenight.eventbrite.com<br/>- Regular: €5<br/>- Walk-in: €10 - Pay with Lydia at the event</p> <p>🔹Games provided<br/>🔹Game masters<br/>🔹Assigned area with tables to play in groups<br/>🔹Ticket includes 1 free drink</p> <p>This Meetup is an initiative of www.thecatchmaker.de</p> ",
   "how_to_find_us": "Lydia will be there to welcome you",
   "visibility": "public",
   "member_pay_fee": false
   },
   {
   "created": 1571213258000,
   "duration": 16200000,
   "id": "26570727233434",
   "name": "IoT and Smart Hardware Showcase 2019",
   "rsvp_limit": 200,
   "date_in_series_pattern": false,
   "status": "upcoming",
   "time": 1573144200000,
   "local_date": "2019-11-07",
   "local_time": "17:30",
   "updated": 1571213258000,
   "utc_offset": 3600000,
   "waitlist_count": 0,
   "yes_rsvp_count": 27,
   "group": {
   "created": 1328820641000,
   "name": "Internet of Things Munich",
   "id": 3265392,
   "join_mode": "open",
   "lat": 48.13999938964844,
   "lon": 11.579999923706055,
   "urlname": "IoTMunich",
   "who": "Sensemakers",
   "localized_location": "München, Germany",
   "state": "",
   "country": "de",
   "region": "en_US",
   "timezone": "Europe/Berlin"
   },
   "link": "https://www.meetup.com/IoTMunich/events/265707272/",
   description: "<p>This event is organized by the hardware pioneers</p> <p>REQUIRED TO ATTEND: Download a FREE TICKET here ...</p>",
   "visibility": "public",
   "member_pay_fee": false
   },
   {
   "created": 1550042729000,
   "duration": 10800000,
   "id": "258922181222",
   "name": "108. JUG-München Treffen",
   "rsvp_limit": 30,
   "date_in_series_pattern": false,
   "status": "upcoming",
   "time": 1573664400000,
   "local_date": "2019-11-13",
   "local_time": "18:00",
   "updated": 1550042729000,
   "utc_offset": 3600000,
   "waitlist_count": 0,
   "yes_rsvp_count": 1,
   "venue": {
   "id": 25942014,
   "name": "Wirtshaus zum Isartal",
   "lat": 48.112571716308594,
   "lon": 11.553250312805176,
   "repinned": true,
   "address_1": "Brudermühlstrasse 2",
   "city": "München",
   "country": "de",
   "localized_country_name": "Germany"
   },
   "group": {
   "created": 1537211427000,
   "name": "Joomla User Group München",
   "id": 29852639,
   "join_mode": "open",
   "lat": 48.13999938964844,
   "lon": 11.579999923706055,
   "urlname": "Joomla-User-Group-Munchen",
   "who": "Mitglieder",
   "localized_location": "München, Germany",
   "state": "",
   "country": "de",
   "region": "en_US",
   "timezone": "Europe/Berlin"
   },
   "link": "https://www.meetup.com/Joomla-User-Group-Munchen/events/258922181/",
   description: "<p>Komm zum JUG-München Treffen und…</p> <p>- lerne nette Leute kennen, die sich mit Joomla! beschäftigen...</p>",
   visibility: "public",
   "member_pay_fee": false
   },
   {
   "created": 1550042767000,
   "duration": 10800000,
   "id": "344wew45345",
   "name": "109. JUG-München Treffen",
   "rsvp_limit": 30,
   "date_in_series_pattern": false,
   "status": "upcoming",
   "time": 1576083600000,
   "local_date": "2019-12-11",
   "local_time": "18:00",
   "updated": 1550042767000,
   "utc_offset": 3600000,
   "waitlist_count": 0,
   "yes_rsvp_count": 1,
   "venue": {
   "id": 25942014,
   "name": "Wirtshaus zum Isartal",
   "lat": 48.112571716308594,
   "lon": 11.553250312805176,
   "repinned": true,
   "address_1": "Brudermühlstrasse 2",
   "city": "München",
   "country": "de",
   "localized_country_name": "Germany"
   },
   "group": {
   "created": 1537211427000,
   "name": "Joomla User Group München",
   "id": 29852639,
   "join_mode": "open",
   "lat": 48.13999938964844,
   "lon": 11.579999923706055,
   "urlname": "Joomla-User-Group-Munchen",
   "who": "Mitglieder",
   "localized_location": "München, Germany",
   "state": "",
   "country": "de",
   "region": "en_US",
   "timezone": "Europe/Berlin"
   },
   "link": "https://www.meetup.com/Joomla-User-Group-Munchen/events/258922189/",
   "description": "<p>Komm zum JUG-München Treffen und…</p> <p>- lerne nette Leute kennen, die sich mit Joomla! beschäftigen<br/>- tausche Dich in lockerer Umgebung beim Stammtisch mit Gleichgesinnten aus<br/>- erhalte Hilfe zur Selbsthilfe und stelle Fragen an andere User und Profis<br/>- höre Dir Vorträge über und rund um Joomla! an oder halte selbst welche<br/>- nimm an Workshops teil oder vielleicht magst Du selbst einen veranstalten?<br/>- teile Dein Wissen und Deine Erfahrungen mit Joomla! oder Erweiterungen<br/>- erfahre aktuelle Informationen aus erster Hand rund um Joomla! oder Joomla!-Events<br/>- profitiere von unseren tollen Lokations und melde Dich heute noch zum Treffen an</p> ",
   "visibility": "public",
   "member_pay_fee": false
   },
   {
   "created": 1556806424000,
   "duration": 10800000,
   "id": "26110504433",
   "name": "Teams UserGroup - Ignite Review",
   "rsvp_limit": 40,
   "date_in_series_pattern": false,
   "status": "upcoming",
   "time": 1574269200000,
   "local_date": "2019-11-20",
   "local_time": "18:00",
   "updated": 1571909707000,
   "utc_offset": 3600000,
   "waitlist_count": 4,
   "yes_rsvp_count": 47,
   "group": {
   "created": 1505650894000,
   "name": "Microsoft Teams Meetup Munich",
   "id": 25956792,
   "join_mode": "open",
   "lat": 48.13999938964844,
   "lon": 11.579999923706055,
   "urlname": "Microsoft-Teams-Meetup-Munich",
   "who": "Members",
   "localized_location": "München, Germany",
   "state": "",
   "country": "de",
   "region": "en_US",
   "timezone": "Europe/Berlin"
   },
   "link": "https://www.meetup.com/Microsoft-Teams-Meetup-Munich/events/261105044/",
   description: "<p>Hallo zusammen,</p> <p>so kurz nach der Microsoft Ignite in Orlando kann es nur ein Thema geben: Die größte Microsoft Veranstaltung der Welt.<br/>Holt Euch die wichtigsten Informationen von der Ignite direkt von den Experten die vor Ort waren.</p> <p>18:00 Uhr - Registrierung<br/>18:30 Uhr - Begrüßung<br/>18:35 Uhr - Ignite Review 1: Wir blicken zurück auf die Microsoft Ignite 2019 (Teil 1)<br/>19:10 Uhr - Pause mit Pizza und Getränken<br/>19:30 Uhr - Ignite Review 2: Wir blicken zurück auf die Microsoft Ignite 2019 (Teil 2)<br/>20:00 Uhr - Fragen und Antworten<br/>20:20 Uhr - Gemeinsame Gespräche und Networking</p> <p>Ihr wollt in einer anderen Stadt an dem MeetUp teilnehmen?</p> <p>Bochum:<br/><a href=\"https://www.meetup.com/de-DE/Microsoft-Teams-MeetUp-Bochum/events/261106864/\" class=\"linkified\">https://www.meetup.com/de-DE/Microsoft-Teams-MeetUp-Bochum/events/261106864/</a></p> <p>Hamburg:<br/><a href=\"https://www.meetup.com/de-DE/Skype-for-Business-User-Group-Hamburg/events/265897255/\" class=\"linkified\">https://www.meetup.com/de-DE/Skype-for-Business-User-Group-Hamburg/events/265897255/</a></p>",
   visibility: "public",
   "member_pay_fee": false
   },
   {
   "created": 1567432094000,
   "duration": 10800000,
   "id": "264495082",
   "name": "Mastering the Linux Command Line & Principles of Continuous Delivery and DevOps",
   "rsvp_limit": 120,
   "date_in_series_pattern": false,
   "status": "upcoming",
   "time": 1573581600000,
   "local_date": "2019-11-12",
   "local_time": "19:00",
   "updated": 1570554830000,
   "utc_offset": 3600000,
   "waitlist_count": 8,
   "yes_rsvp_count": 132,
   "venue": {
   "id": 26112492,
   "name": "Google",
   "lat": 48.143035888671875,
   "lon": 11.541084289550781,
   "repinned": true,
   "address_1": "Erika-Mann-Straße 33",
   "city": "München",
   "country": "de",
   "localized_country_name": "Germany"
   },
   "group": {
   "created": 1565272185000,
   "name": "OpenValue München",
   "id": 32563109,
   "join_mode": "open",
   "lat": 48.13999938964844,
   "lon": 11.579999923706055,
   "urlname": "OpenValueMuenchen",
   "who": "Members",
   "localized_location": "München, Germany",
   "state": "",
   "country": "de",
   "region": "en_US",
   "timezone": "Europe/Berlin"
   },
   "link": "https://www.meetup.com/OpenValueMuenchen/events/264495082/",
   "description": "<p>Bert Jan Schrijver - Two topics</p> <p>Agenda</p> <p>19:00 Networking<br/>19:30 First topic (see below)<br/>20:30 Break<br/>20:45 Second topic (see below)</p> <p>1) Mastering the Linux command line</p> <p>As a developer, you often have to deal with Linux servers. Troubleshooting, digging through logs, editing configuration files, you name it. If you're used to working with Windows or OSX GUI's, the Linux terminal might appear fairly basic and difficult to use.<br/>But, with some basic background knowledge and a small set of terminal commands in your toolbox, it can actually be extremely powerful and loads of fun!<br/>In this session, I'll explain the concepts behind the Linux command line and I'll demo loads of useful stuff. You'll learn how to quickly navigate, find files, examine and search through logs, how to investigate a system under load, a bit of shell scripting, ssh tunneling and more!<br/>At the end of this session, you'll have the chance to throw your own problems and use cases at me - I'll come up with solutions on the spot. Bring your own problems ;-)<br/>This talk takes places entirely in the command line. No slides, no IDE, just a plain terminal window. After this session, you'll be on your way to master the Linux command line yourself!</p> <p>2) Better software, faster: Principles of Continuous Delivery and DevOps</p> <p>The Wall Street Journal already mentioned it in 2011: “Software is eating the world.” Nowadays, every company is an IT company. Product owners and other business representatives seeing their competitors release new features to end users every day are demanding the same from their own software teams. How do you measure up to this heavy pressure as an IT organization? How do you quickly make changes to software systems in fast-paced environments without losing your grip on quality? How do you build and test software in such a way that it's always in a releasable state? This session explains the principles of continuous delivery and DevOps. You’ll leave with enough insights into how and where to get started yourself.</p> <p>About the Speaker: Bert Jan Schrijver is CTO at OpenValue and focuses on Java, Continuous Delivery and DevOps. Bert Jan is a Java Champion, JavaOne Rock Star speaker, Duke's Choice Award winner and leads NLJUG, the Dutch Java User Group. He loves to share his experience by speaking at conferences, writing for the Dutch Java magazine and helping out Devoxx4Kids with teaching kids how to code. Bert Jan is easily reachable on Twitter at @bjschrijver.</p> ",
   "visibility": "public",
   "pro_is_email_shared": false,
   "member_pay_fee": false
   },
   {
   "created": 1570631402000,
   "duration": 1800000,
   "id": "265531605222",
   "name": "Webinar: Build the Right Things by Voyagent, Inc. Founder",
   "date_in_series_pattern": false,
   "status": "upcoming",
   "time": 1573068600000,
   "local_date": "2019-11-06",
   "local_time": "20:30",
   "updated": 1570631601000,
   "utc_offset": 3600000,
   "waitlist_count": 0,
   "yes_rsvp_count": 11,
   "group": {
   "created": 1570531441000,
   "name": "Product School Munich",
   "id": 32863959,
   "join_mode": "open",
   "lat": 48.13999938964844,
   "lon": 11.579999923706055,
   "urlname": "Product-School-Munich",
   "who": "Members",
   "localized_location": "München, Germany",
   "state": "",
   "country": "de",
   "region": "en_US",
   "timezone": "Europe/Berlin"
   },
   "link": "https://www.meetup.com/Product-School-Munich/events/265531605/",
   description: "<p>***RSVP on EventBrite: <a href=\"https://prdct.school/2Mp55jL\" class=\"linkified\">https://prdct.school/2Mp55jL</a> ***</p> <p>*** DISCLAIMER: This event is ONLINE ***</p> <p>Too many startup founders begin with an idea and jump straight into execution without validating their idea in the market early and often. When they release their product, it doesn't resonate with their target users. As the founders continue to pivot in search of product-market fit, they burn cash until they eventually run out. In this session, Eric will show you the philosophy, frameworks, and tools you can use to drastically increase your chance of success by decreasing the cost of development and ensuring you're building a product that solves an urgent need.</p> <p>Main takeaways:<br/>- How to create a user-centered culture and design process<br/>- How to leverage data and analytics to drive product decisions<br/>- How to tightly integrate the product leaders, engineers, and customers<br/>- How to validate product/feature ideas quickly and with the lowest cost<br/>- How to create an idea meritocracy</p> <p>Meet the Speaker: Eric Weiss</p> <p>With almost 15 years of experience building technology products in a variety of roles, Eric can transform companies into streamlined and effective organizations with a shared purpose. He is currently a Founder at Voyagent and at Full Cycle Product Development.</p> <p>Get Eric's book \"Build the Right Things: How to Design and Build a Product People Will Love\" here (<a href=\"https://www.amazon.com.mx/Build-Right-Things-Product-English-ebook/dp/B07XXHH5DS\" class=\"linkified\">https://www.amazon.com.mx/Build-Right-Things-Product-English-ebook/dp/B07XXHH5DS</a>)</p> <p>View Speaker's Full Profile (<a href=\"https://prod.school/2OvXVwI\" class=\"linkified\">https://prod.school/2OvXVwI</a>)</p> <p>Get the FREE Product Book here (<a href=\"https://prdct.school/2CMSqF1\" class=\"linkified\">https://prdct.school/2CMSqF1</a>)</p> <p>Get Your Tickets (<a href=\"https://prdct.school/2Mp55jL\" class=\"linkified\">https://prdct.school/2Mp55jL</a>)</p> <p>*Entrance not guaranteed without valid ticket from Eventbrite</p>",
   visibility: "public",
   "member_pay_fee": false
   },
   {
   "created": 1543406706000,
   "duration": 32400000,
   "id": "256774760",
   "name": "Hack&Jump - Munich's bus tour for coders & developers",
   "date_in_series_pattern": false,
   "status": "upcoming",
   "time": 1573124400000,
   "local_date": "2019-11-07",
   "local_time": "12:00",
   "updated": 1566905829000,
   "utc_offset": 3600000,
   "waitlist_count": 0,
   "yes_rsvp_count": 34,
   "venue": {
   "id": 26120186,
   "name": "HANS IM GLÜCK Burgergrill & Bar",
   "lat": 48.12040710449219,
   "lon": 11.603134155273438,
   "repinned": false,
   "address_1": "St.-Martin-Straße 57",
   "city": "München",
   "country": "de",
   "localized_country_name": "Germany"
   },
   "group": {
   "created": 1501244830000,
   "name": "Tech_Hub München",
   "id": 25186228,
   "join_mode": "open",
   "lat": 48.13999938964844,
   "lon": 11.579999923706055,
   "urlname": "Tech_Hub-Munchen",
   "who": "Members",
   "localized_location": "München, Germany",
   "state": "",
   "country": "de",
   "region": "en_US",
   "timezone": "Europe/Berlin"
   },
   "link": "https://www.meetup.com/Tech_Hub-Munchen/events/256774760/",
   description: "<p>Join our IT-Job-Shuttle to the digital economy of Munich. During the tour, you can look behind the scenes of high-tech companies and have valuable contacts to IT-professionals of the participating companies. Catering will be provided all day. To the end of the day we have a Get-Together and serve good food and free beer.</p> <p>Steig ein in den IT-Job-Shuttle durch die Münchner Digitalwirtschaft. Während der mehrstündigen Tour kannst Du hinter die Kulissen von Hightech-Unternehmen schauen und wertvolle Kontakte zu Fachleuten und Personalern in den beteiligten Unternehmen knüpfen. Für die Verpflegung zwischendurch ist bestens gesorgt. Zum Ausklang des Abends erwarten Dich dann nochmal gutes Essen und Freibier.</p> <p>#hightech #kaffeefahrt #ITjobs</p> <p>Join us: www.hack-and-jump.de and please REGISTER HERE <a href=\"https://www.eventbrite.de/e/hackjump-der-it-job-shuttle-in-munchen-2019-tickets-50166116204\" class=\"linkified\">https://www.eventbrite.de/e/hackjump-der-it-job-shuttle-in-munchen-2019-tickets-50166116204</a> - if you don't have a ticket jet - please register!</p>",
   visibility: "public",
   "member_pay_fee": false
   },
   {
   "created": 1571223250000,
   "duration": 7200000,
   "id": "265709123333",
   "name": "Best Startups from Hamburg - Pitchnight#1 - München",
   "rsvp_limit": 200,
   "date_in_series_pattern": false,
   "status": "upcoming",
   "time": 1579111200000,
   "local_date": "2020-01-15",
   "local_time": "19:00",
   "updated": 1571770971000,
   "utc_offset": 3600000,
   "waitlist_count": 0,
   "yes_rsvp_count": 18,
   "group": {
   "created": 1571221326000,
   "name": "Wow Yes Startups - München",
   "id": 32898396,
   "join_mode": "open",
   "lat": 48.13999938964844,
   "lon": 11.579999923706055,
   "urlname": "wow-yes-Startups-Munchen",
   "who": "Mitglieder",
   "localized_location": "München, Germany",
   "state": "",
   "country": "de",
   "region": "en_US",
   "timezone": "Europe/Berlin"
   },
   "link": "https://www.meetup.com/wow-yes-Startups-Munchen/events/265709123/",
   description: "<p>HAMBURG’S BEST STARTUPS VISIT MUNICH</p> <p>we connect startups with matching investors.</p> <p>Wir laden alle Startups, Investoren und sonstige Interessierte herzlich ein, an diesem Abend dabei zu sein!</p> <p>Die fünf Gewinner unserer Hamburger Startup Competition pitchen ihr Business vor interessierten Investoren und Publikum in München. Wir freuen uns auf einen tollen Abend in entspannter Atmosphäre!</p> <p>Ablauf:</p> <p>Beginn um 19:00 Uhr<br/>Pitch eines erfolgreichen, lokalen Startups<br/>5 Pitches der besten Hamburger Startups<br/>Q&amp;A mit Münchner Investoren und Startup Community<br/>Lokale Jury wählt das Gewinnerstartup des Abends<br/>Networking an der Bar<br/>Ende um 22:00 Uhr</p> <p>Alle Infos zu uns und unseren Events findest Du hier: <a href=\"https://www.meetup.com/de-DE/wow-yes-Startups-Munchen/\" class=\"linkified\">https://www.meetup.com/de-DE/wow-yes-Startups-Munchen/</a></p> <p>******************************************</p> <p>ENGLISH</p> <p>You are a startup, investor or just curious about the startup community? Then you are cordially invited to meet Hamburg’s best startups in Munich!</p> <p>The five winners of our Hamburg Startup Competition will pitch their business in front of interested investors and the public in Munich. We are looking forward to a great evening in a relaxed atmosphere!</p> <p>Agenda:</p> <p>Start at 7 p.m.<br/>Pitch of a successful, local startup<br/>5 pitches from Hamburg’s best startups<br/>Q&amp;A with Munich investors and startup community<br/>Local jury selects the winner startup of the evening<br/>Networking at the bar<br/>End at 10 p.m.</p> <p>You can find all information about us and our events here: <a href=\"https://www.meetup.com/de-DE/wow-yes-Startups-Munchen/\" class=\"linkified\">https://www.meetup.com/de-DE/wow-yes-Startups-Munchen/</a></p> ",
   visibility: "public",
   "member_pay_fee": false
   },
   {
   "created": 1571083854000,
   "duration": 7200000,
   "id": "265668928xx3",
   "name": "Abendworkshop - Inner-Leadership: Ein innovativer Ansatz für Transformation",
   "rsvp_limit": 60,
   "date_in_series_pattern": false,
   "status": "upcoming",
   "time": 1572285600000,
   "local_date": "2019-10-28",
   "local_time": "19:00",
   "updated": 1571854601000,
   "utc_offset": 3600000,
   "waitlist_count": 5,
   "yes_rsvp_count": 60,
   "venue": {
   "id": 25615449,
   "name": "Henley Business School Germany",
   "lat": 48.13741683959961,
   "lon": 11.58404541015625,
   "repinned": true,
   "address_1": "Maximilianstraße 40",
   "city": "München",
   "country": "de",
   "localized_country_name": "Germany"
   },
   "group": {
   "created": 1510684582000,
   "name": "Leadership Events - München",
   "id": 26598849,
   "join_mode": "open",
   "lat": 48.13999938964844,
   "lon": 11.579999923706055,
   "urlname": "Leadership-Events-Munchen",
   "who": "Mitglieder",
   "localized_location": "München, Germany",
   "state": "",
   "country": "de",
   "region": "en_US",
   "timezone": "Europe/Berlin"
   },
   "link": "https://www.meetup.com/Leadership-Events-Munchen/events/265668928/",
   "description": "<p>Inner-Leadership ist der grundlegendste Ansatz für jede Transformation und ein erfülltes und erfolgreiches Leben. Das Bewusstsein für den eigenen Umgang mit sich selbst, ist unser langfristiges Kapital - persönlich, unternehmerisch und gesellschaftlich. Unsere psychologische und physische Fitness, mentale Resilienz und emotionale Intelligenz sind die Voraussetzung dafür, unser höchstes Potenzial zu entfalten und zu leben.</p> <p>Unternehmen, die dies neben den persönlichen Werten und dem individuellen Wachstum ihrer Mitarbeiter in den Vordergrund stellen, folgen dem Zeitgeist. Um die beste Version ihrer Selbst zu werden, unterstützen sie ihre Mitarbeiter in der Entwicklung ihres höchsten Potentials. Inner-Leadership bricht einschränkende, nicht hilfreiche Gewohnheiten, Überzeugungen und Verhaltensweisen auf und ebnet den Weg für eine nachhaltige und messbare Transformationsenergie - im innen und außen.</p> <p>In diesem Monday@Henley gibt Henley Alumna Dr. Eva Gattnar Einblicke, wie dies gelingen kann. Durch Nutzung von innovativen Methoden können wir ein Bewusstsein für den eigenen Umgang mit uns selbst schaffen, um unsere innere Fitness, mentale und emotionale Stärke für mehr Erfüllung, mehr Belastbarkeit und mehr Lebensqualität nachhaltig, mit messbarem Erfolg, aufzubauen. Actualize yourself and become your highest version!</p> <p>Wir beginnen wie immer mit Networking um 18.30 Uhr und der Workshop startet um 19 Uhr; das Ende ist für 21 Uhr geplant, gefolgt von einer halben Stunde Networking zum Ausklang.</p> ",
   "how_to_find_us": "Der Eingang befindet sich am Thomas-Wimmer Ring, Ecke Hildegardstraße (///gams.aufheben.alge). Dort im 2. Stock.",
   "visibility": "public",
   "member_pay_fee": false
   },
   {
   "local_time": "19:00",
   "local_date": "2019-10-31",
   "link": "https://www.meetup.com/Djembe-and-Percussion-Fun-Munchen/events/265750801/",
   "visibility": "public_limited",
   "group": {
   "created": 1376421848000,
   "name": "Djembe and Percussion Fun Muenchen",
   "id": 9795322,
   "join_mode": "approval",
   "lat": 48.13999938964844,
   "lon": 11.579999923706055,
   "urlname": "Djembe-and-Percussion-Fun-Munchen",
   "who": "Munich Percussionists",
   "localized_location": "München, Germany",
   "state": "",
   "country": "de",
   "region": "en_US",
   "timezone": "Europe/Berlin"
   },
   "waitlist_count": 0,
   "yes_rsvp_count": 3,
   "duration": 7200000,
   "time": 1572544800000,
   "utc_offset": 3600000,
   "name": "Neue Regeln für neue Mitglieder",
   "id": "265750801"
   },
   {
   "created": 1569143472000,
   "duration": 7200000,
   "id": "26506289833331",
   "name": "Elementor MeetUp München - November 2019",
   "date_in_series_pattern": false,
   "status": "upcoming",
   "time": 1574186400000,
   "local_date": "2019-11-19",
   "local_time": "19:00",
   "updated": 1570709361000,
   "utc_offset": 3600000,
   "waitlist_count": 0,
   "yes_rsvp_count": 5,
   "venue": {
   "id": 26638286,
   "name": "Heinrich Marketing GmbH",
   "lat": 48.14986038208008,
   "lon": 11.549469947814941,
   "repinned": true,
   "address_1": "Nymphenburger Str. 58",
   "address_2": "Hinterhof, rechts",
   "city": "München",
   "country": "de",
   "localized_country_name": "Germany"
   },
   "group": {
   "created": 1549966106000,
   "name": "Elementor München",
   "id": 31146435,
   "join_mode": "open",
   "lat": 48.13999938964844,
   "lon": 11.579999923706055,
   "urlname": "Muenchen-Elementor-Meetup",
   "who": "Mitglieder",
   "localized_location": "München, Germany",
   "state": "",
   "country": "de",
   "region": "en_US",
   "timezone": "Europe/Berlin"
   },
   "link": "https://www.meetup.com/Muenchen-Elementor-Meetup/events/265062898/",
   "description": "<p>Einzelheiten werden noch bekannt gegeben</p> ",
   "visibility": "public",
   "pro_is_email_shared": false,
   "member_pay_fee": false
   },
   {
   "created": 1571559775000,
   "id": "26581051422",
   "name": "Halloween",
   "date_in_series_pattern": false,
   "status": "upcoming",
   "time": 1572552000000,
   "local_date": "2019-10-31",
   "local_time": "21:00",
   "updated": 1571559833000,
   "utc_offset": 3600000,
   "waitlist_count": 0,
   "yes_rsvp_count": 12,
   "venue": {
   "id": 26691826,
   "name": "upside east",
   "lat": 48.12247848510742,
   "lon": 11.606674194335938,
   "repinned": false,
   "address_1": "Rosenheimer Str. 145 D",
   "city": "München",
   "country": "DE",
   "localized_country_name": "Germany"
   },
   "group": {
   "created": 1570119258000,
   "name": "For active Singles",
   "id": 32843927,
   "join_mode": "open",
   "lat": 48.13999938964844,
   "lon": 11.579999923706055,
   "urlname": "for-those-who-hates-being-alone",
   "who": "Mitglieder",
   "localized_location": "München, Germany",
   "state": "",
   "country": "de",
   "region": "en_US",
   "timezone": "Europe/Berlin"
   },
   "link": "https://www.meetup.com/for-those-who-hates-being-alone/events/265810514/",
   "description": "<p>Hey Guys,<br/>Let's celebrate Halloween at upside east (Ostbahnhof) It's a nice location with a rooftop bar. I'll be there at 9pm and will wait for you inside the club</p> ",
   "visibility": "public",
   "member_pay_fee": false
   },
   {
   "created": 1561546757000,
   "duration": 7200000,
   "id": "262637434",
   "name": "#NoEstimates-How to improve software development predictability & profitability",
   "rsvp_limit": 140,
   "date_in_series_pattern": false,
   "status": "upcoming",
   "time": 1573493400000,
   "local_date": "2019-11-11",
   "local_time": "18:30",
   "updated": 1571905670000,
   "utc_offset": 3600000,
   "waitlist_count": 0,
   "yes_rsvp_count": 125,
   "venue": {
   "id": 25852478,
   "name": "ThoughtWorks Munich ",
   "lat": 48.135372161865234,
   "lon": 11.613633155822754,
   "repinned": true,
   "address_1": "Bothestraße 11",
   "city": "München",
   "country": "de",
   "localized_country_name": "Germany"
   },
   "group": {
   "created": 1413448074000,
   "name": "ThoughtWorks Munich",
   "id": 17658472,
   "join_mode": "open",
   "lat": 48.13999938964844,
   "lon": 11.579999923706055,
   "urlname": "ThoughtWorks-Muenchen",
   "who": "Mitglieder",
   "localized_location": "München, Germany",
   "state": "",
   "country": "de",
   "region": "en_US",
   "timezone": "Europe/Berlin"
   },
   "link": "https://www.meetup.com/ThoughtWorks-Muenchen/events/262637434/",
   description: "<p>TW hosts: #NoEstimates-How to improve software development predictability and profitability by focusing on what matters</p> <p>In this Meetup, your basic assumptions about the role of estimation will be challenged.</p> <p>We will share how to be sure to deliver on time, no matter whether you use estimates or not! You already know that many things go wrong, no matter how well you try to estimate. People are assigned 10% to a project, or work in 4 different projects at the same time. Managers fight to get experts assigned to their projects, and that creates unforeseen delays and problems. Not to mention illnesses, people changing jobs, promotions, etc. Forget all of that. You can account for all of those “unexpected” events. And you can do it without estimates! Yes, without estimates!</p> <p>We’ll look into cases where estimation is the core failure pattern in projects, and why they happen. We’ll look into how to overcome those failure patterns, and help you know what is the real progress in your project without asking all the teams to sit down and endlessly discuss what the size of a story is.</p> <p>[ Bonus: If you are interested in learning the details of how to do it, Vasco Duarte is organizing a 1-day workshop where we dive deeper into the techniques and tools that allow you to put #NoEstimates into action and save your project! To know more about the full-day #NoEstimates Workshop (November 12th) &amp; Product Owner Success Toolkit Workshop (November 11th), go here: <a href=\"https://oikosofyseries.com/workshops-by-vasco-duarte-product-owner-success-toolkit-and-noestimates\" class=\"linkified\">https://oikosofyseries.com/workshops-by-vasco-duarte-product-owner-success-toolkit-and-noestimates</a> ]</p> <p>About the Presenter<br/># Vasco Duarte, Author of #NoEstimates, Speaker &amp; Co-Founder at Oikosofy<br/>Product Manager, Scrum Master, Project Manager, Director, Agile Coach - only some of the roles that he has taken in software development organizations. Having worked in the software industry since 1997, and Agile practitioner since 2004. He has worked in small, medium and large software organizations as an Agile Coach or leader in agile adoption at those organizations. He was one of the leaders of Agile methods and Agile culture adoption at Avira, Nokia, F-Secure.</p> <p>AGENDA:<br/>18:30 Snacks, drinks and mingle<br/>19:00 Talk and questions<br/>20:00 More questions, drinks and mingle</p> <p>SNACKS:<br/>As always we are offering various snacks and, beer and soft drinks. No full meal, but at least something to eat.</p>",
   how_to_find_us: "The entrance is right next to the entrance of the big bike shop “Stadler”. If you are standing in front of the entrance of Holiday Inn you have to go around the whole building to find our entrance.",
   "visibility": "public",
   "member_pay_fee": false
   },
   {
   "created": 1548145714000,
   "duration": 7200000,
   "id": "258288773",
   "name": "Wie Sie den Mehrwert eines PMOs sichtbar machen können",
   "date_in_series_pattern": false,
   "status": "upcoming",
   "time": 1573754400000,
   "local_date": "2019-11-14",
   "local_time": "19:00",
   "updated": 1548145714000,
   "utc_offset": 3600000,
   "waitlist_count": 0,
   "yes_rsvp_count": 9,
   "venue": {
   "id": 25697058,
   "name": "Schuhbecks Orlando Lounge ",
   "lat": 48.13831329345703,
   "lon": 11.580145835876465,
   "repinned": true,
   "address_1": "Platzl 4  ",
   "city": "München",
   "country": "de",
   "localized_country_name": "Germany"
   },
   "group": {
   "created": 1516184773000,
   "name": "Project Management Office Stammtisch München - PMO-Meetup",
   "id": 27185043,
   "join_mode": "open",
   "lat": 48.13999938964844,
   "lon": 11.579999923706055,
   "urlname": "Project-Management-Office-Stammtisch-Munchen-PMO-Meetup",
   "who": "Members",
   "localized_location": "München, Germany",
   "state": "",
   "country": "de",
   "region": "en_US",
   "timezone": "Europe/Berlin"
   },
   link: "https://www.meetup.com/Project-Management-Office-Stammtisch-Munchen-PMO-Meetup/events/258288773/",
   description: "<p>Die Arbeit eines PMOs ist häufig von Widerständen begleitet. Ein PMO kostet Geld, kann für manche Kollegen lästig sein und auch als überflüssiger Overhead gelten. Im Rahmen einer Verschlankung könnte es daher schnell dem Rotstift zum Opfer fallen. Umso wichtiger ist es für die Verantwortlichen, den Mehrwert fundiert darstellen zu können. Welche Möglichkeiten es dafür gibt, darum geht es an diesem Abend.</p> <p>Nach einer kurzen Einführung sammeln die Teilnehmer in Arbeitsgruppen Ideen. Diese werden dann gemeinsam präsentiert und diskutiert. Tauschen Sie sich intensiv mit Ihren Peers aus und erweitern Sie Ihr Netzwerk. Jetzt gleich kostenlos anmelden.</p> <p>Achtung, die Plätze sind begrenzt. Bitte unbedingt vorher kostenlos anmelden unter <a href=\"https://www.theprojectgroup.com/pmo-stammtisch\" class=\"linkified\">https://www.theprojectgroup.com/pmo-stammtisch</a></p> <p>Und noch was: Werfen Sie unbedingt auch einen Blick auf das Programm unserer kostenlosen Webinare. Das Programm wird laufend aktualisiert: <a href=\"https://www.theprojectgroup.com/webinar\" class=\"linkified\">https://www.theprojectgroup.com/webinar</a></p>",
   how_to_find_us: "Bitte unbedingt vorher kostenlos anmelden unter https://www.theprojectgroup.com/pmo-stammtisch",
   "visibility": "public",
   "member_pay_fee": false
   }
 ]
 };